### ISSUE TITLE
[BROKEN LINK] Broken link in Terms of Use webpage

### ISSUE THREAD

**Issue by LB-BartoszDudzinski** [o3de/o3debinaries.org#21]
## Which page has the broken link?

https://www.o3debinaries.org/license
## Which link was broken?

https://www.github.com/o3de/

The link related to the O3DE github repository is broken. The name is displayed correctly, however it leads to the .org domain and tries to open the https://www.github.org/o3de/ webpage.
## Know where it should go?

https://github.com/o3de

**Comment by amzn-changml** [comment]
This has been corrected as of https://github.com/o3de/o3debinaries.org/commit/00035a99fa481b04797bb3ed8751929b10c68bd7
